version: "3"

services:
  db:
    container_name: 'emkk-db'
    image: postgres
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    env_file:
      - ./backend/db.env
    ports:
    - "5432:5432"

  backend:
    container_name: 'emkk-backend'
    image: emkk_backend
    build: ./backend
    volumes:
      - ./backend:/emkk/backend
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    container_name: 'emkk-frontend'
    image: emkk_frontend
    build: ./frontend
    command: npm run start
    env_file:
      - ./frontend/.env
    volumes:
      - /emkk/frontend/node_modules
      - ./frontend:/emkk/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
